[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm --prefix client ci", "npm --prefix server install"]

[phases.build]
cmds = ["npm --prefix client run build"]

[start]
cmd = "npm --prefix server start"
